name: Verify

# no trigger on tags, only `verify` the push, so merged PRs then only need to be `deploy`ed
on:
  push:
    branches: ['**']

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022]
        jdk: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - uses: s4u/maven-settings-action@v2.8.0
        with:
          # avoid a default entry for "github"
          githubServer: false
          servers: >
            [
              { "id": "github", "username": "${{ github.actor }}", "password": "${env.GITHUB_TOKEN}" },
              { "id": "github-cops-lab-test-utils", "username": "${{ github.actor }}", "password": "${env.GITHUB_TOKEN}" },
              { "id": "github-cops-lab-commons", "username": "${{ github.actor }}", "password": "${env.GITHUB_TOKEN}" }
            ]

      - name: Build Project (Maven)
        # "install" needed for the build of restapi
        run: mvn -B -ntp clean install
        env:
          # auth necessary to access GitHub Maven registries
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build REST API (Maven)
        run: |
          cd analyzer/restapi-plugin
          mvn -B -ntp clean verify spring-boot:repackage
        env:
          # auth necessary to access GitHub Maven registries
          GITHUB_TOKEN: ${{ github.token }}
